adx_contentsnippetid: 9dea5191-712b-f011-8c4c-6045bd078e56
adx_contentsnippetlanguageid: fda88e9f-84a9-433e-aa99-5397dc5359ce
adx_display_name: FetchXML - Values by Branch
adx_name: FetchXML - Values by Branch
adx_type: 756150001
